### ISSUE TITLE
Lavatomb Quake II logos and VIS

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo-data#96] opened 2017-03-28 18:24 UTC
Lavatomb has too many Quake II logos all over the place, they should probably be removed or replaced with a Quetoo logo.

I also noticed a problem (Probably VIS issue) on Lavatomb while recording some cinematic demos, there's a single missing face in a specific area (Crouch on the pillar in the screenshot, flying around that cave also has the same result)

![Screenshot](https://cdn.discordapp.com/attachments/224935404506316800/296347613442211840/quetoo028.png)

**Comment by kaadmy** [comment] 2017-03-28 18:26
CC @Panjoo

**Comment by Panjoo** [comment] 2017-03-29 23:46
You're kidding me, you see a problem with those logos in a Quake2 tribute map?
 👎 

Making them textures+normals was a considerable amount of work and they just belong in this map. 
Now if I had a whole range of cool Quetoo logos and banners I would probably think about replacing some of them. Maybe.
At a later time I might edit some of the banner textures though, but not at this moment.

This VIS error is a classic HOM error, caused by the fact that Quetoo doesn't have a way of using patch meshes for these kind of complex shapes. All has to be done with brushes and it's always a source of errors and troubles. But I'm glad you found this HOM, I'll try to get rid of it as soon as possible.

**Comment by kaadmy** [comment] 2017-03-29 23:52
I like the way the logos look, but directly using the Quake II logo in a game not endorsed etc by id or Bethesda isn't a good idea IMHO.

**Comment by jdolan** [comment] 2017-03-30 12:11
From a legal standpoint, the Quake2 logos will likely hurt us. It becomes [much] more problematic when we consider Steam. Valve has already asked for us to form a legal entity, and to inventory all of our licenses, so that they can review the legality of our project before they will grant us access to the distribution platform. It would be a liability for Valve to allow us to publish a game that infringes on copyrights through their platform.

This isn't top priority, I don't think it has to be addressed right now. I think there are a dozen other legal pitfalls that could kill our Steam dreams first, so we can cross this bridge when we get to it.

**Comment by jdolan** [comment] 2017-03-30 12:11
CC @Paril

**Comment by Paril** [comment] 2017-03-30 13:17
We need to absolutely avoid any potential legal avenues if we are to
appease Valve. Quetoo logos would be better.

**Comment by Panjoo** [comment] 2017-03-30 13:31
To be honest here, I never had any Steam dreams to begin with. I'm just not a big fan of the legal bs it brings. For instance some dork who has nothing to do with the project and isn't even a fan starts to whine about it on a Steam forum, and next thing you know we can scrap all dm remakes. And if that ever happens I'm going to quit, I guarantee you that.

Look at all the QuakeLive banners the mappers had to put in their _own maps_ in order to have their maps used. So they already get maps made by fans for free and now they can claim the maps because the authors had to agree with their offer. They know very well that some dude who's made a nice map is going to comply, he's just happy that his work is going to be used at all. 
They should celebrate the fact that some people take the time and effort to even _want_ to use their old game logos to dress up maps. Call it product placement, they should be thanking us. I know it's not that simple but of course that's how it should be.

The skull and strogg-wing textures are staying but I could maybe try and use something else for the single q2 logo texture. Any good ideas for ornament textures that don't have anything to do with the Quake/Stroggos universe and isn't a Quetoo logo. Love to hear it.

**Comment by Paril** [comment] 2017-03-30 13:34
The skull and strogg wings aren't trademarked afaik so you are fine with
keeping those, it's only the Q2 logo itself that would be problematic.
Also, keep in mind that this only applies to the data we put in the initial
release; ain't nobody saying you can't use the Q2 logo in fan maps or
workshop content, which we could always nudge our users towards. We have a
lot of ways to avoid it, but for our main release/official content we
should avoid that big legal concern. The maps themselves are entirely
within fair use, but a trademarked logo is not.

**Comment by jdolan** [comment] 2017-03-30 13:45
Regarding Steam, to be perfectly honest: I won't be heartbroken if Quetoo never makes it there, either. It would be incredibly cool if it does -- I'd love to reach more players, and have a shipped Steam title on my resume. But even if it doesn't ultimately happen for legal reasons, we should continue to push for it as long and as hard as we can. Look at all of the traction we've gained in the community just through the Greenlight campaign. It's clearly worth pursuing until we absolutely can not.

**Comment by Paril** [comment] 2017-03-30 13:50
Agree entirely. The Unix crowd really love it.

**Comment by Panjoo** [comment] 2017-03-31 20:40
https://github.com/jdolan/quetoo-data/commit/3247cbf7d4a7d6d4ec4d004e9c55e48cf6175230

Both issues have been fixed. Closing.

I might as well do the same with the one Q2 logo in Slimyplace, dunno what to put there yet. 
Thinking about stuff takes time:/

**Closed by Panjoo** 2017-03-31 20:40 UTC
