### ISSUE TITLE
Specular values

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo-data#98] opened 2017-04-01 04:51 UTC
I was messing around with Xonotic and trying to see how their specular looked, and apparently Quetoo's specular seems pretty much correct.

The problem is, it's _way_ too glossy, making everything look unlit and made of glass or something.

I tried to tune it a bit by changing the global CVars: `r_specular 0.3; r_specular 0.5`.

Before:

![Gotta enable images, did you really think this would work?](https://cdn.discordapp.com/attachments/224935404506316800/297591950586937344/quetoo_specular_before.png)

After:

![Gotta enable images, did you really think this would work?](https://cdn.discordapp.com/attachments/224935404506316800/297592031625084928/quetoo_specular_after.png)

Any thoughts on this, and whether we should reduce specular for all/most materials?

**Comment by TenaciousTigerTrumpets** [comment] 2017-04-21 13:33
This is just a brainfart, but I think what would make the specular potentially look better is to somehow approximate ambient specular. Perhaps there could be a low energy specular that is "smeared" across the entire hemisphere. It you picmip to some average value then there's a lot of areas where you only get the specular when you're at the "correct" angle to see it. But that's not very realistic, in reality, there's light coming out of all directions on the hemisphere. I think most games nowadays games use cubemaps for hemispherical specular and analytic specular for light entities. Maybe, just using some subtle and very broad specular highlight that is visible at any angle (using simply the surface normal?), and then having a sharper specular on top of that to approximate the material more closely would make things look better. Of course, that implies rendering two highlights per surface -- should be cheap anno 2017.

**Comment by jdolan** [comment] 2017-09-02 12:47
I'm not really sure what to do with this ticket. The way I see it, we could:

1) Tediously rewrite all of our materials files, and re-zip each map.
2) Change the default `r_specular` cvar value to `0.5`.
3) Do nothing, just live with it.

Option 2 is the most pragmatic, but I'd like to get @Panjoo 's input before we consider any action.

**Comment by Panjoo** [comment] 2017-11-05 22:47
> ... before we consider any action.

Apparently some things have already been played with? I was exprimenting with the cl_editor and loaded up aerowalk. Odd that I didn't really notice this sooner, but I'm not too happy with this butt ugly over-exposure effect:
![ugly1](https://user-images.githubusercontent.com/10857572/32419757-94bcada8-c27f-11e7-84a7-7989a40380fe.jpg)
![ugly2](https://user-images.githubusercontent.com/10857572/32419759-997852a2-c27f-11e7-90a6-fb849651fcc2.jpg)
And it's not just in aerowalk of course.

> **kaadmy**: I was messing around with Xonotic and trying to see how their specular looked, and apparently Quetoo's specular seems pretty much correct.
The problem is, it's way too glossy, making everything look unlit and made of glass or something.
I tried to tune it a bit by changing the global CVars: r_specular 0.3; r_specular 0.5.

Are you talking about quetoo's specular or xonotic's?

I don't really understand what is going on here. Why are these values being altered? His 'before' shot looks way better than the 'after' shot, especially when you view the images one after the other in a viewer. Looks much more vivid.
If textures don't look right isn't that what the seperate materials are for? This shouldn't be done global.
Seriously, I'd like this reverted completely.

**Comment by kaadmy** [comment] 2017-11-05 22:51
I was talking about Quetoo when I said specular looked wrong, but it definitely looks a bit more washed out now with the new shader changes. Since the shaders now seems changed for the better most of the time I might say the current material values are out of whack and might look better with some tweaks.

**Comment by jdolan** [comment] 2017-11-05 22:57
Void-995 has been working on our shaders, and he's made some notable improvements to the accuracy of the lighting model. He's also pointed out some issues in quemap, and is working on implementing a more modern radiosity.

As @kaadmy said, his changes will require tweaks to some maps (especially once radiosity is in place). For the most part, I think it'll be setting global light scale parameters via worldspawn, and maybe reducing hardness on a few materials. You don't have to take all of this work on, Pan. We can divide and conquer.

Btw, Rage, Edge and Warehouse are probably the best examples of what the new shaders look like.

**Comment by Paril** [comment] 2017-11-06 01:36
A lot of our code for specular/bump was entirely wrong, so Void had fixed that. Things look like they should if the code was written properly, and we consolidated a few things. We were always looking at a result that was calculated wrong, especially in the case of a texture having no bumpmap as specular didn't affect them at all.

@Panjoo the concept is that the textures (normal map, specular map and diffuse) should be set up so that they look perfect with the default r_specular/hardness/parallax/modulate values and not require individual tweaking in the shader files. The only use-case I can see for keeping these values is if we have textures that use the same diffuse/specular/normal set but require different values, but I don't know how often we use that in the game currently. That's only a concept though and hasn't been done to the game yet.

**Comment by SpineyPete** [comment] 2018-02-21 16:12
Is this still an issue? The maps look mostly fine imo.

**Comment by jdolan** [comment] 2018-02-21 16:48
I think Aerowalk looks pretty good. The small 16x16 blue floor lights are not quite bright enough anymore imo, but the overall lighting looks acceptable. Looking forward to seeing this puppy with HDR and indirect lighting!

**Comment by SpineyPete** [comment] 2018-02-21 16:51
Yeah I **did** scale down the surface lights since they looked too bright, but I might have overdone (underdone?) it. The thing is though, those overexposed bits near the top were mostly due to surface light, not due to sunlight (in fact, toggling sunlight did literally nothing to those areas).

**Comment by jdolan** [comment] 2018-02-21 16:55
That's weird, because surface lights have an exponential attenuation in quemap, where point lights are linear. So, you would think, that surface lights wouldn't bleed too far across large areas like that.

Maybe a better way to handle them would be with point lights or even small spot lights. We could also consider adding those cute little "light volumes" we have on Trial by Error.

**Comment by jdolan** [comment] 2018-03-04 13:07
I'm going to close this issue out. All maps will need tuning for the indirect lighting stuff coming in Void's branch. We can revisit Aerowalk specifically then. #108 will be the place to address all of that.

**Closed by jdolan** 2018-03-04 13:07 UTC
